### PR TITLE
Add a snapcraft badge

### PR DESCRIPTION
**Pull request by evandandrea**
Congrats on the htmldoc snap! Here's a build status badge.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
Sadly, snapcraft and FLTK-based applications do not get along; see:

    https://bugs.launchpad.net/htmldoc/+bug/1630281

**Comment by michaelrsweet** [comment]
Figured out how to fix the X11 issues...

**Comment by michaelrsweet** [comment]
OK, so I've added this to the HTMLDOC home page instead:

    https://michaelrsweet.github.io/htmldoc

**Comment by evandandrea** [comment]
Thanks Michael!

**Pull request closed without merging**
